# Generated by Django 4.2.26 on 2025-11-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_partcategory_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
